### ISSUE TITLE
dpm configuration and storage of credentials

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpmpy#2]
- [x] Key variables: username, password, endpoint - registry location (url)
- [x] Format: standard ini file
- [x] location ~/.dpm/config
- [x] Compute the "active" config at runtime, pass it down to subcommands [can you set this at "class" level in some reasonable way]
- [ ] [Optional] support --config flag which can override
- [ ] [Optional or separate issue] support dpm configure command that sets this stuff up for you (with prompts ...)

**Comment by rgrp** [comment]
Prompt on error:

```
ERROR: missing user credentials.

To enter your credentials please run:

dpm configure
```

**Comment by Fak3** [comment]
should work as described
